<?php

namespace app\components;

use yii\base\Widget;
use app\components\TreeAsset;
use yii\helpers\Html;

class TreeWidget extends Widget
{

    public $model;
    private $className="";
    private $data=[];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(get_class($this->model)){
            $this->className = \yii\helpers\StringHelper::basename(get_class($this->model));
            $this->className = strtolower($this->className);
        }
        $this->data = $this->model->find()->asArray()->all();
    }

    private function getList($parent=0)
    {
        return Html::ul($this->getChildren($parent),['item' => function($item, $index) {
            $itemCode=Html::a($item['name'],'/'.$this->className.'/'.$item['id']);
            if($this->getChildren($item['id'])) {
                $itemCode.=$this->getList($item['id']);
            }
            return Html::tag(
                'li',
                $itemCode
            );
        }, 'class'=>'tree-widget']);
    }

    private function getChildren($parent_id)
    {
        $children = [];
        foreach ($this->data as $datum)
        {
            if($datum['parent_id']==$parent_id){
                array_push($children,$datum);
            }
        }
        return $children;
    }

    public function run()
    {
        TreeAsset::register($this->view);
        return $this->getList();
    }
}